[package]
name = "jp"
version = "0.2.0"
authors = ["Christoph Burgmer <christoph.burgmer@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
serde_json = "1.0.39"
jsonpath_lib = "0.2.3"
clap = "2.33.0"
